### ISSUE TITLE
Extra offset in z?

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndtilecache#11]
On line 107 of https://github.com/openconnectome/ocptilecache/blob/master/tilecache/tile.py, it looks like the zindex is incremented by 1. Any reason this is different than x or y? Seems to be causing issues if the project z dimension is < cube dimension. 

@kunallillaney @randalburns thoughts?

**Comment by kunallillaney** [comment]
@alexbaden I will look into this. I am in the middle of re-implementing a bunch of stuff here.

**Comment by randalburns** [comment]
This looks like a bug that's left over from when we used to have the z-dimension as a slicerange, rather than normalized to x and y.  I likely didn't change the tilecache when I changed the ocpcadb, now spdb.  I think it's safe to change, test (lightly) and redploy.

**Comment by kunallillaney** [comment]
this now works. The bug was in oldchannel stuff. You will have to clear the tilecache before this will work. I cleared the cache for Fear199 res5 and you can access slice 0.
http://dsp029.pha.jhu.edu/ocptilecache/tilecache/mcfc/Fear199/Grayscale:G/xy/0/0_0_5.png
Here is the non mcfc version which also works
http://dsp029.pha.jhu.edu/ocptilecache/tilecache/Fear199/Grayscale/xy/0/0_0_5.png
